### ISSUE TITLE
[Error] Exception: Object reference not set to an instance of an object after updating to 1.20.0-rc-6

### ISSUE THREAD

**Issue by morggin** [sekelsta/detailedanimals#6]
After updating to 1.20.0-rc6 i'm getting a similar error to Shmitty after trying to save world changes from rc-5 to rc-6 transition:

25.12.2024 01:50:51 [Error] Couldn't add entity type game:hare-female-darkbrown at 4085917.6, 115, 4100552.68 due to exception in code. Will remove from chunk, sorry!
25.12.2024 01:50:51 [Error] Exception: Object reference not set to an instance of an object.
at Genelib.AnimalHunger.ApplyNutritionEffects() in /home/tiffany/main/projects/vs_mods/detailedanimals/src/Genelib/Entity/Behavior/AnimalHunger.cs:line 211
at Genelib.AnimalHunger.Initialize(EntityProperties properties, JsonObject typeAttributes) in /home/tiffany/main/projects/vs_mods/detailedanimals/src/Genelib/Entity/Behav>
at Vintagestory.API.Common.Entities.EntitySidedProperties.loadBehaviors(Entity entity, EntityProperties properties, IWorldAccessor world) in VintagestoryApi\Common\Entity>
at Vintagestory.API.Common.Entities.EntityProperties.Initialize(Entity entity, ICoreAPI api) in VintagestoryApi\Common\Entity\EntityProperties.cs:line 253
at Vintagestory.API.Common.Entities.Entity.Initialize(EntityProperties properties, ICoreAPI api, Int64 InChunkIndex3d) in VintagestoryApi\Common\Entity\Entity.cs:line 582
at Vintagestory.API.Common.EntityAgent.Initialize(EntityProperties properties, ICoreAPI api, Int64 InChunkIndex3d) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 121
at Vintagestory.Server.ServerMain.LoadEntity(Entity entity, Int64 fromChunkIndex3d) in VintagestoryLib\Server\ServerMain.cs:line 2264
25.12.2024 01:50:51 [Error] Couldn't add entity type game:hare-female-gold at 4086009.38, 109.5, 4100375.47 due to exception in code. Will remove from chunk, sorry!

**Comment by morggin** [comment]
this is with mod version detailedanimals_0.3.3

**Comment by sekelsta** [comment]
Fixed by a1c73eeae8efbbeda8ed5e1c0978a9245b877065
